<Project>

  <PropertyGroup>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1901;NU1902;NU1903;NU1904</WarningsNotAsErrors>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
    <DebugType>full</DebugType>
    <ArtifactsDir>$(MSBuildThisFileDirectory)artifacts\</ArtifactsDir>
    <ArtifactsBinDir>$(ArtifactsDir)bin\</ArtifactsBinDir>
    <ArtifactsObjDir>$(ArtifactsDir)obj\</ArtifactsObjDir>
    <ArtifactsPublishDir>$(ArtifactsDir)publish\</ArtifactsPublishDir>
    <RunSettingsFilePath>$(MSBuildThisFileDirectory)src\.runsettings</RunSettingsFilePath>
  </PropertyGroup>

  <PropertyGroup>
    <BaseOutputPath>$(ArtifactsBinDir)$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(ArtifactsObjDir)$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)src\stylecop.json" />
  </ItemGroup>

</Project>
